import Testing
import Foundation
@testable import Memora

@MainActor
struct AudioFileTests {

    @Test("AudioFile の初期値が正しい")
    func initialValues() {
        let file = AudioFile(title: "テスト録音", audioURL: "/tmp/test.m4a")
        #expect(file.title == "テスト録音")
        #expect(file.audioURL == "/tmp/test.m4a")
        #expect(file.duration == 0)
        #expect(file.isTranscribed == false)
        #expect(file.isSummarized == false)
        #expect(file.isLifeLog == false)
        #expect(file.summary == nil)
        #expect(file.keyPoints == nil)
        #expect(file.actionItems == nil)
        #expect(file.projectID == nil)
        #expect(file.lifeLogTags.isEmpty)
    }

    @Test("projectID を設定できる")
    func setProjectID() {
        let projectID = UUID()
        let file = AudioFile(title: "PJ付き", audioURL: "/tmp/pj.m4a", projectID: projectID)
        #expect(file.projectID == projectID)
    }

    @Test("要約フィールドを更新できる")
    func updateSummaryFields() {
        let file = AudioFile(title: "要約テスト", audioURL: "/tmp/summary.m4a")

        file.summary = "テスト要約"
        file.keyPoints = "ポイント1, ポイント2"
        file.actionItems = "アクション1"
        file.isSummarized = true

        #expect(file.isSummarized == true)
        #expect(file.summary == "テスト要約")
        #expect(file.keyPoints == "ポイント1, ポイント2")
        #expect(file.actionItems == "アクション1")
    }

    @Test("録音時間を設定できる")
    func setDuration() {
        let file = AudioFile(title: "長さテスト", audioURL: "/tmp/dur.m4a")
        #expect(file.duration == 0)

        file.duration = 120.5
        #expect(file.duration == 120.5)
    }

    @Test("文字起こし済みフラグを切り替えられる")
    func toggleTranscribed() {
        let file = AudioFile(title: "転写テスト", audioURL: "/tmp/tr.m4a")
        #expect(file.isTranscribed == false)

        file.isTranscribed = true
        #expect(file.isTranscribed == true)
    }

    @Test("ライフログフィールドを設定できる")
    func setLifeLogFields() {
        let file = AudioFile(title: "LLテスト", audioURL: "/tmp/ll.m4a")
        #expect(file.isLifeLog == false)
        #expect(file.lifeLogTags.isEmpty)

        file.isLifeLog = true
        file.lifeLogTags = ["meeting", "important"]
        #expect(file.isLifeLog == true)
        #expect(file.lifeLogTags == ["meeting", "important"])
    }

    @Test("ID が自動生成される")
    func autoGeneratedID() {
        let file1 = AudioFile(title: "A", audioURL: "/tmp/a.m4a")
        let file2 = AudioFile(title: "B", audioURL: "/tmp/b.m4a")
        #expect(file1.id != file2.id)
    }
}
