import Testing
import Foundation
@testable import Memora

@MainActor
struct TodoItemTests {

    @Test("TodoItem の初期値が正しい")
    func initialValues() {
        let item = TodoItem(title: "テストタスク")
        #expect(item.title == "テストタスク")
        #expect(item.notes == nil)
        #expect(item.assignee == nil)
        #expect(item.speaker == nil)
        #expect(item.priority == "medium")
        #expect(item.dueDate == nil)
        #expect(item.isCompleted == false)
        #expect(item.completedAt == nil)
        #expect(item.projectID == nil)
    }

    @Test("全パラメータを指定して作成できる")
    func initWithAllParameters() {
        let dueDate = Date().addingTimeInterval(86400)
        let projectID = UUID()
        let item = TodoItem(
            title: "フルタスク",
            notes: "メモ",
            assignee: "田中",
            speaker: "話者1",
            priority: "high",
            dueDate: dueDate,
            relativeDueDate: "明日",
            projectID: projectID
        )
        #expect(item.title == "フルタスク")
        #expect(item.notes == "メモ")
        #expect(item.assignee == "田中")
        #expect(item.speaker == "話者1")
        #expect(item.priority == "high")
        #expect(item.dueDate == dueDate)
        #expect(item.relativeDueDate == "明日")
        #expect(item.projectID == projectID)
    }

    @Test("完了状態をトグルできる")
    func toggleCompleted() {
        let item = TodoItem(title: "トグルテスト")
        #expect(item.isCompleted == false)
        #expect(item.completedAt == nil)

        item.isCompleted = true
        item.completedAt = Date()
        #expect(item.isCompleted == true)
        #expect(item.completedAt != nil)

        item.isCompleted = false
        item.completedAt = nil
        #expect(item.isCompleted == false)
        #expect(item.completedAt == nil)
    }

    @Test("ID が自動生成される")
    func autoGeneratedID() {
        let item1 = TodoItem(title: "A")
        let item2 = TodoItem(title: "B")
        #expect(item1.id != item2.id)
    }

    @Test("優先度のバリエーション")
    func priorityVariants() {
        let low = TodoItem(title: "低", priority: "low")
        let medium = TodoItem(title: "中", priority: "medium")
        let high = TodoItem(title: "高", priority: "high")
        #expect(low.priority == "low")
        #expect(medium.priority == "medium")
        #expect(high.priority == "high")
    }
}
