import Testing
import Foundation
@testable import Memora

@MainActor
struct TranscriptTests {

    @Test("Transcript の初期値が正しい")
    func initialValues() {
        let audioFileID = UUID()
        let transcript = Transcript(audioFileID: audioFileID, text: "こんにちは")
        #expect(transcript.audioFileID == audioFileID)
        #expect(transcript.text == "こんにちは")
        #expect(transcript.speakerLabels.isEmpty)
        #expect(transcript.segmentStartTimes.isEmpty)
        #expect(transcript.segmentEndTimes.isEmpty)
        #expect(transcript.segmentTexts.isEmpty)
    }

    @Test("スピーカーセグメントを追加できる")
    func addSpeakerSegment() {
        let transcript = Transcript(audioFileID: UUID(), text: "")
        transcript.addSpeakerSegment(speakerLabel: "Speaker 1", startTime: 0.0, endTime: 5.2, text: "おはようございます")
        transcript.addSpeakerSegment(speakerLabel: "Speaker 2", startTime: 5.2, endTime: 10.0, text: "こんにちは")

        #expect(transcript.speakerLabels.count == 2)
        #expect(transcript.segmentStartTimes.count == 2)
        #expect(transcript.segmentEndTimes.count == 2)
        #expect(transcript.segmentTexts.count == 2)

        #expect(transcript.speakerLabels[0] == "Speaker 1")
        #expect(transcript.segmentStartTimes[1] == 5.2)
        #expect(transcript.segmentTexts[1] == "こんにちは")
    }

    @Test("ID が自動生成される")
    func autoGeneratedID() {
        let t1 = Transcript(audioFileID: UUID(), text: "A")
        let t2 = Transcript(audioFileID: UUID(), text: "B")
        #expect(t1.id != t2.id)
    }

    @Test("テキストを更新できる")
    func updateText() {
        let transcript = Transcript(audioFileID: UUID(), text: "元のテキスト")
        #expect(transcript.text == "元のテキスト")

        transcript.text = "更新後のテキスト"
        #expect(transcript.text == "更新後のテキスト")
    }

    @Test("複数セグメントの整合性")
    func multipleSegmentsConsistency() {
        let transcript = Transcript(audioFileID: UUID(), text: "")
        for i in 0..<5 {
            transcript.addSpeakerSegment(
                speakerLabel: "話者\(i)",
                startTime: Double(i) * 10.0,
                endTime: Double(i + 1) * 10.0,
                text: "セグメント\(i)"
            )
        }

        #expect(transcript.speakerLabels.count == 5)
        #expect(transcript.segmentStartTimes.count == 5)
        #expect(transcript.segmentEndTimes.count == 5)
        #expect(transcript.segmentTexts.count == 5)

        // 各配列が同じインデックスで対応していることを確認
        for i in 0..<5 {
            #expect(transcript.speakerLabels[i] == "話者\(i)")
            #expect(transcript.segmentStartTimes[i] == Double(i) * 10.0)
            #expect(transcript.segmentEndTimes[i] == Double(i + 1) * 10.0)
            #expect(transcript.segmentTexts[i] == "セグメント\(i)")
        }
    }
}
